apiVersion: v1
kind: ServiceAccount
metadata:
  name: xdxct-vgpu-device-manager
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xdxct-vgpu-device-manager
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/eviction
  verbs:
  - get
  - list
  - watch
  - update
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdxct-vgpu-device-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xdxct-vgpu-device-manager
subjects:
- kind: ServiceAccount
  name: xdxct-vgpu-device-manager
  namespace: default

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: xdxct-vgpu-device-manager-ds
  namespace: default
  labels:
    app: vgpu-dm
spec:
  selector:
    matchLabels:
      app: vgpu-dm
  template:
    metadata:
      labels:
        app: vgpu-dm
    spec:
      serviceAccount: xdxct-vgpu-device-manager
      serviceAccountName: xdxct-vgpu-device-manager
      containers:
      - name: xdxct-vgpu-device-manager
        image: hub.xdxct.com/kubevirt/xdxct-vgpu-device-manager:devel
        imagePullPolicy: IfNotPresent
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          value: "default"
        - name: CONFIGFILE
          value: "/configfile/config-vgpu.yaml"
        - name: DEFAULTVGPUCONFIG
          value: "PANGU-A0-1G-1-CORE"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: container-sys
        - mountPath: /configfile
          name: configfile
      volumes:
      - name: configfile
        configMap:
          name: xdxct-vgpu-config-file
      - name: container-sys
        hostPath:
          path: /sys
          type: Directory


